# Generated by Django 4.0.6 on 2022-08-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('rodado', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('talle', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Appventas')),
                ('disponibilidad', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appventas.categorias')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.DeleteModel(
            name='accesorios',
        ),
        migrations.DeleteModel(
            name='bicicletas',
        ),
        migrations.DeleteModel(
            name='indumentaria',
        ),
        migrations.DeleteModel(
            name='repuestos',
        ),
    ]
