# Generated by Django 4.0.6 on 2022-08-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0003_categorias_producto_delete_accesorios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
