# Generated by Django 4.0.6 on 2022-08-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0004_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='activo',
            field=models.BooleanField(),
        ),
    ]
