# Generated by Django 4.0.6 on 2022-08-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0005_alter_categorias_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='activo',
        ),
    ]
